/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automat;

import java.io.IOException;

/**
 *
 * @author Thomas
 */
public class GUI_master extends javax.swing.JFrame {
    Billetautomat BA = new Billetautomat();
    
    public void setIndex(int i){
        jTabbedPane1.setSelectedIndex(i);
    }
    /**
     * Creates new form GUI_master
     */
    public GUI_master() throws IOException {
        initComponents();
        
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_master.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
       
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GUI_master().setVisible(true);
//            }
        
        
//        });
        this.setVisible(true);
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        gUI_mLogin2 = new automat.GUI_mLogin();
        gUI_billettype2 = new automat.GUI_billettype(BA);
        gUI_IndbetalP2 = new automat.GUI_IndbetalP();
        gUI_mM2 = new automat.GUI_mM();
        gUI_printB2 = new automat.GUI_printB();
        gUI_hovedmenu1 = new automat.GUI_hovedmenu(jTabbedPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Montør login", gUI_mLogin2);
        jTabbedPane1.addTab("Billettype", gUI_billettype2);
        jTabbedPane1.addTab("Indbetal penge", gUI_IndbetalP2);
        jTabbedPane1.addTab("Montør menu", gUI_mM2);
        jTabbedPane1.addTab("Print billet", gUI_printB2);
        jTabbedPane1.addTab("Hovedmenu", gUI_hovedmenu1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
     
                }
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private automat.GUI_IndbetalP gUI_IndbetalP2;
    private automat.GUI_billettype gUI_billettype2;
    private automat.GUI_hovedmenu gUI_hovedmenu1;
    private automat.GUI_mLogin gUI_mLogin2;
    private automat.GUI_mM gUI_mM2;
    private automat.GUI_printB gUI_printB2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}

